### ISSUE TITLE
Can't connect to WiFi networks

### ISSUE THREAD

**Issue by QuentinI** [tpwrules/nixos-apple-silicon#225] opened 2024-08-04 21:38 UTC
After updating my 2021 MBP 14' I couldn't connect to any WiFI networks anymore. I eventually found [this](https://github.com/raspberrypi/linux/issues/6049#issuecomment-2259734713) workaround for a similar issue with Raspberry Pi, and adding `brcmfmac.feature_disable=0x82000` to `boot.kernelParams` solved the problem.

I don't know if this affects anyone else and whether it's something this project would want to handle at all and if yes, then what the preferred way would be (make it default, make it an optional toggle, just mention it in README), so I'm just opening this issue to hopefully save people who might run into similar issues some time, because I don't think I've seen any mention of this workaround specifically in connection to Asahi anywhere.

Please feel free to close this as the actual issue on my end is solved.

**Comment by tpwrules** [comment] 2024-08-05 03:58
Can you try changing the kernel tag to `asahi-6.9.12-2`? I couldn't replicate the issue myself but the Asahi folks say that contains fixes in the WiFi driver.

There is also this: http://lists.infradead.org/pipermail/hostap/2024-August/042893.html

**Comment by qazer2687** [comment] 2024-08-05 09:31
I have the same issue on my m2 mba, the workaround doesn't work for me though. How do you change the kernel tag?

**Comment by damien-biasotto** [comment] 2024-08-05 11:50
@qazer2687  I couldn't find an easy way to override the `linux-asahi` `src` attribute (overrideAttrs is not available). 

So I created a fork and changed the kernel tag there. And I can confirm the tag `asahi-6.9.12-2` fixes the issue on my end.


You can use it by changing the url of the nixos-apple-silicon input
```    
nixos-apple-silicon = {
  url = "github:damien-biasotto/nixos-apple-silicon/bugfix/wifi";
  inputs.nixpkgs.follows = "nixpkgs";
};
```

**Comment by crawfordlong** [comment] 2024-08-05 16:20
I've been hit by this and of course immediately after garbage collecting away working builds. Is there any way to temporarily bring WiFi back up from a system without a network connection?

**Comment by kavfkah** [comment] 2024-08-06 20:43
6.9.12-2 doesn't work for me, reverting back to 6.9.9-7 does

**Comment by diegobfernandez** [comment] 2024-08-06 22:27
It has been mentioned by Asahi official mastodon account: https://social.treehouse.systems/@AsahiLinux/112909897657710314
Looks like there is a workaround.
> For those who have already updated, adding brcmfmac.feature_disable=0x82000 to your kernel command line should work around the issue and make WiFi work again, allowing you to update to the fix once it is released.

**Comment by montchr** [comment] 2024-08-09 14:18
I'm holding off on updating the kernel on my laptop, but can confirm that the following config addition fixed the issue for me:

```nix
boot.kernelParams = [ "brcmfmac.feature_disable=0x82000" ];
```

**Comment by crawfordlong** [comment] 2024-08-11 18:50
Still no luck for me. I have a working version (on 24.05), but if I update it or switch to unstable, still no wifi (that's with or without the kernelParams addition above). There is reference to a fix on Asahi Fedora, so hopefully will be along shortly for NixOS?

**Comment by segment-tree** [comment] 2024-08-13 00:07
> Still no luck for me. I have a working version (on 24.05), but if I update it or switch to unstable, still no wifi (that's with or without the kernelParams addition above). There is reference to a fix on Asahi Fedora, so hopefully will be along shortly for NixOS?

you may try `nixos-rebuild boot` to update efi?

**Comment by arminius-smh** [comment] 2024-08-14 09:21
> Still no luck for me. I have a working version (on 24.05), but if I update it or switch to unstable, still no wifi (that's with or without the kernelParams addition above). There is reference to a fix on Asahi Fedora, so hopefully will be along shortly for NixOS?

There is now a patched version of wpa_supplicant in nixos-unstable: https://github.com/NixOS/nixpkgs/pull/333091

My wifi didn't work with the kernelParams as well, but it does with this patch, if you now update your system again on unstable, it should hopefully work

**Comment by tpwrules** [comment] 2024-09-04 02:54
Should be fixed in the latest release, apologies for the delays.

**Closed by tpwrules** 2024-09-04 02:54 UTC
