### ISSUE TITLE
custom logo support doesn't work

### ISSUE THREAD

**Issue by zzywysm** [tpwrules/nixos-apple-silicon#110] opened 2023-10-18 19:15 UTC
In pull request https://github.com/tpwrules/nixos-apple-silicon/pull/22 support for a custom boot logo was introduced.   It doesn't work because the code references a shell script "makelogo.sh" that isn't included in the pull request, which leads to this error:

```
building '/nix/store/jgsii7p57irk7dgil70dg905jq2cvcwr-m1n1-1.4.3.drv'...
unpacking sources
unpacking source archive /nix/store/yaqclg8zr7v26wrnikxcdqdkym83czx1-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
/nix/store/p7ww8q44jswpxr5m1kqcmf8zx8qc2qs8-stdenv-linux/setup: line 136: ./makelogo.sh: cannot execute: required file not found
/nix/store/p7ww8q44jswpxr5m1kqcmf8zx8qc2qs8-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/jgsii7p57irk7dgil70dg905jq2cvcwr-m1n1-1.4.3.drv' failed with exit code 127
error: 1 dependencies of derivation '/nix/store/rhhikp8xaccjpjw0aq3r6dqvh2ral57r-nixos-system-greenrosetta-23.11.20230915.d433649.drv' failed to build
```

The line I added to my configuration.nix to test this code path is:

`boot.m1n1CustomLogo = ./bootlogo_256.png;`

**Comment by tpwrules** [comment] 2023-10-21 03:31
This would have worked at the time, the problem is https://github.com/AsahiLinux/m1n1/pull/332 which is not in a released version of nixos-apple-silicon yet.

Regardless, this will be fixed for the next release. Thanks for catching it early.

**Closed** 2023-10-21 17:30 UTC
