### ISSUE TITLE
Accelerated graphics no longer work

### ISSUE THREAD

**Issue by rowanG077** [tpwrules/nixos-apple-silicon#126] opened 2023-12-20 22:21 UTC
Since the update today my system has fallen back to the software opengl implementation `llvmpipe`. I'm running a 14 inch M2 Max Macbook pro. An easy way to confirm whether this is the case is to use the following command:

```
nix-shell -p glxinfo --run 'glxinfo | grep "OpenGL renderer string: "'
```

This shows the following for me:

```
OpenGL renderer string: llvmpipe (LLVM 16.0.6, 128 bits)
```

I'm currently trying to `overlay` mesa instead of `replace` to see if that makes any difference.

**Comment by rowanG077** [comment] 2023-12-20 23:00
It may be a problem that we are not using a correct kernel config? At the very least I have the kernel blaring about `Failed to get dp-xbar: -517` Which according to [here](https://github.com/chadmed/asahi-overlay/issues/51) means `CONFIG_MUX_APPLE_DPXBAR` is missing. which is indeed not set in the config.

**Comment by tpwrules** [comment] 2023-12-21 01:38
Running a Plasma Wayland desktop session, on my machine (2021 M1 Max 16" MBP), I get `OpenGL renderer string: Apple M1 Max (G13C C0)` from the given command and acceleration does seem to work properly.

I did unfortunately neglect to synchronize the kernel configs. I will address this for the next release. Were you able to confirm that enabling that option fixed your issue?

**Comment by rowanG077** [comment] 2023-12-21 05:21
I can confirm that it fixes the issue. The backlight control also wasn't working without it.

**Comment by tpwrules** [comment] 2023-12-21 05:40
I'll close this once the fix makes it to a release. Thanks for contributing.

**Comment by CodeWitchBella** [comment] 2023-12-21 15:11
I can confirm that this fix works for me as well :+1: 

Also, I think the proper place to get the fedora config is here: https://copr-dist-git.fedorainfracloud.org/cgit/@asahi/kernel/kernel.git/tree/kernel-aarch64-fedora.config
It's even a git repo (http://copr-dist-git.fedorainfracloud.org/git/@asahi/kernel/kernel.git), so it should be possible to integrate using fetchgit instead of copying the full file verbatim.

**Comment by tpwrules** [comment] 2023-12-23 05:18
Fixed in the latest release. I ran into issues simply copying the config verbatim, so I only took the Apple Silicon-specific changes. It's a little clunky but it meets my goals (short build time, ease of maintenance, compatibility with Apple Silicon and NixOS).

**Closed by tpwrules** 2023-12-23 05:18 UTC
