### ISSUE TITLE
linux-asahi-edge Rust support is broken with nixpkgs master

### ISSUE THREAD

**Issue by yu-re-ka** [tpwrules/nixos-apple-silicon#66] opened 2023-03-25 22:33 UTC
bisected this to https://github.com/nixos/nixpkgs/commit/7de3f08ce38aca9fddb5db7bcb7741fd389be9ef

**Comment by bkchr** [comment] 2023-03-25 23:50
Duplicate of https://github.com/tpwrules/nixos-apple-silicon/issues/63

**Closed** 2023-03-26 00:19 UTC
